services:
  bluebubbles:
    container_name: bluebubbles
    image: sickcodes/docker-osx:naked
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - SHORTNAME=monterey
      - IMAGE_PATH=/image
      - BOOTDISK=/bootdisk
      - EXTRA=-display none -vnc 0.0.0.0:99,password-secret=secvnc0 -object secret,id=secvnc0,data=${VNC_PASSWORD}
      - ADDITIONAL_PORTS=hostfwd=tcp::1234-:1234,
      - DISPLAY=:99
      - WIDTH=${WIDTH}
      - HEIGHT=${HEIGHT}
      - NOPICKER=true
    dns:
      - ${DNS_SERVER}
    devices:
      - /dev/kvm:/dev/kvm
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${CONFIG_PATH}/maindisk.qcow2:/image
      - ${CONFIG_PATH}/bootdisk.qcow2:/bootdisk
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      # BlueBubbles server API (handles its own auth)
      - "traefik.http.routers.${SUBDOMAIN}.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.services.${SUBDOMAIN}.loadbalancer.server.port=1234"
    ports:
      - 5999:5999

networks:
  frontend:
    external: true
