homeassistant:
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto:1883
serial:
  port: tcp://10.0.0.222:6638
  baudrate: 115200
  adapter: ember
  disable_led: false
advanced:
  transmit_power: 20
frontend:
  enabled: true
  port: 8080
version: 4
devices:
  '0xa81710b7eae30000':
    friendly_name: Foco Carpas
  '0xa81710b811be0000':
    friendly_name: Foco Pasillo Oficina
  '0xc4d7fdbbb92b0000':
    friendly_name: Foco Escritorio
  '0xc4d7fdbc1f860000':
    friendly_name: Foco Cuadros
  '0x282c02bfffee4a37':
    friendly_name: Higrometro Oficina
  '0xffffb40e060331ae':
    friendly_name: Control Rojo
