homeassistant:
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto:1883
serial:
  port: tcp://10.0.0.222:6638
  baudrate: 115200
  adapter: ember
  disable_led: false
advanced:
  transmit_power: 20
frontend:
  enabled: true
  port: 8080
version: 4
devices:
  '0xa81710b7eae30000':
    friendly_name: Foco Carpas
  '0xa81710b811be0000':
    friendly_name: Foco Pasillo Oficina
  '0xc4d7fdbbb92b0000':
    friendly_name: Foco Escritorio
  '0xc4d7fdbc1f860000':
    friendly_name: Foco Cuadros
  '0x282c02bfffee4a37':
    friendly_name: Higrometro Oficina
  '0xffffb40e060331ae':
    friendly_name: Control Rojo
  '0xc4d7fdbbb1580000':
    friendly_name: Foco Refrigerador
  '0xc4d7fdbbfb0e0000':
    friendly_name: Foco Fregadero
  '0xc4d7fdbbea210000':
    friendly_name: Foco Sillón Café
  '0xc4d7fdbc27b40000':
    friendly_name: Foco Desayunador
  '0xc4d7fdbbc8670000':
    friendly_name: Foco Escaleras
  '0xc4d7fdbbcd8f0000':
    friendly_name: Foco TV
  '0xc4d7fdbc21b60000':
    friendly_name: Foco Servidor
  '0xc4d7fdbbfecb0000':
    friendly_name: Foco Pasillo Arriba
  '0xc890a81f021f0000':
    friendly_name: Foco Baño Cris
  '0xffffb40e06034997':
    friendly_name: Control Azul
  '0xc890a81e8bde0000':
    friendly_name: Cris 3
  '0xc890a81ef1cb0000':
    friendly_name: Cris 4
  '0x1c784ba0c8700000':
    friendly_name: Cris 1
  '0x1c784ba123890000':
    friendly_name: Cris 2
  '0x001788010874b255':
    friendly_name: Control Cris
